### ISSUE TITLE
Implement Twitter and Google login

### ISSUE THREAD

**Issue by vaibhav-jain18** [vaibhav-jain18/Social-media-integration-app#1]
You can implement Twitter and Google login in this flutter app. As well as you can improve the Documentation of the project.

**Comment by Ritsz123** [comment]
I can work on this please assign this issue to me

**Comment by vaibhav-jain18** [comment]
I have assigned this issue.

**Comment by Ritsz123** [comment]
do you want login without firebase?

**Comment by Ritsz123** [comment]
I will be using firebase for login operations..

**Comment by vaibhav-jain18** [comment]
That's ok.
