### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by Ritsz123** [vaibhav-jain18/Social-media-integration-app#5]
All the details to configure & run the project needs  to be updated.

**Comment by Ritsz123** [comment]
I am working on this..

**Comment by Ritsz123** [comment]
I am working on this issue as soon my PR #4 get's merged I will make another PR for this.

**Comment by vaibhav-jain18** [comment]
I have merged your pr but login is still not working. I have enabled authentication from firebase console.

**Comment by vaibhav-jain18** [comment]
C:\WINDOWS\system32>keytool -list -v -alias androiddebugkey -keystore %USERPROFILE%\.android\debug.keystore
Illegal option:  Jain\.android\debug.keystore
keytool -list [OPTION]...

Lists entries in a keystore

Options:

 -rfc                    output in RFC style
 -alias <alias>          alias name of the entry to process
 -keystore <keystore>    keystore name
 -cacerts                access the cacerts keystore
 -storepass <arg>        keystore password
 -storetype <type>       keystore type
 -providername <name>    provider name
 -addprovider <name>     add security provider by name (e.g. SunPKCS11)
   [-providerarg <arg>]    configure argument for -addprovider
 -providerclass <class>  add security provider by fully-qualified class name
   [-providerarg <arg>]    configure argument for -providerclass
 -providerpath <list>    provider classpath
 -v                      verbose output
 -protected              password through protected mechanism

Use "keytool -?, -h, or --help" for this help message

**Comment by vaibhav-jain18** [comment]
It is showing this.

**Comment by vaibhav-jain18** [comment]
Twitter and Google Login worked but Facebook login is still not working

**Comment by vaibhav-jain18** [comment]
Everything is fine just Fb Login is not working.

**Comment by Ritsz123** [comment]
> Everything is fine just Fb Login is not working.

you need to generate api keys from https://developers.facebook.com/

**Comment by vaibhav-jain18** [comment]
I have generated api keys

**Comment by vaibhav-jain18** [comment]
But there is only APP ID not App secret

**Comment by vaibhav-jain18** [comment]
I have also added Login in that

**Comment by Ritsz123** [comment]
> But there is only APP ID not App secret

https://theonetechnologies.com/blog/post/how-to-get-facebook-application-id-and-secret-key go through this

**Comment by vaibhav-jain18** [comment]
It is still not working

**Comment by vaibhav-jain18** [comment]
It just loads but doesn't work.

**Comment by Ritsz123** [comment]
if you are trying it on emulator give it a shot on physical device

**Comment by vaibhav-jain18** [comment]
I am doing it on a physical device already. My laptop is not capable of running an emulator.

**Comment by vaibhav-jain18** [comment]
Facebook login is working but there is some error, if I login with Google first and then logout then I cannot login with facebook.
